# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 10
 timeout: 30000

# Klic k API na detekci VPN
iphub-key: key

# Zda-li se pujde jenom pripojit z CZ/SK
block-country: false

# Seznam serveru na kterych lze hlasovat
vote-servers:
 - survival
 - skyblock
 - creative
 - vanilla
 - vanillasb
 - prison

# Prometheus statistiky
prometheus:
 state: true
 port: 28026