# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 10
 timeout: 30000

# Klic k API na detekci VPN
iphub-key: key